name: Deploy

inputs:
  roleArn:
    required: true
    type: string
  bucketParamName:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ inputs.roleArn }}
        aws-region: ca-central-1

    - name: Get host bucket name
      id: bucket
      shell: bash
      run: |
        BUCKET_NAME_JSON=$(echo $(aws ssm get-parameter --name ${{ inputs.bucketParamName }} --region 'ca-central-1') | sed 's/ //g' )
        echo "::set-output name=BUCKET_NAME::${BUCKET_NAME_JSON}"
