name: Deploy

inputs:
  roleArn:
    required: true
    type: string
  bucketSsmParamName:
    required: true
    type: string
  distributionSsmParamName:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ inputs.roleArn }}
        aws-region: ca-central-1

    - name: Get host bucket name
      id: bucket
      run: |
        BUCKET_NAME_JSON=$(echo $(aws ssm get-parameter --name ${{ inputs.bucketSsmParamName }} --region 'ca-central-1') | sed 's/ //g' )
        echo "::set-output name=BUCKET_NAME::${BUCKET_NAME_JSON}"
      shell: bash

    - name: Get CloudFront distribution ID
      id: dist
      run: |
        DIST_ID_JSON=$(echo $(aws ssm get-parameter --name ${{ inputs.distributionSsmParamName }} --region 'ca-central-1') | sed 's/ //g' )
        echo "::set-output name=DIST_ID::${DIST_ID_JSON}"
      shell: bash

    - name: Sync to S3
      env:
        BUCKET_NAME: ${{fromJson(steps.bucket.outputs.BUCKET_NAME).parameter.value}}
      run: aws s3 sync ./dist s3://${{ env.BUCKET_NAME }}
      shell: bash

    - name: Invalidate CloudFront distribution path
      env:
        DIST_ID: ${{fromJson(steps.dist.outputs.DIST_ID).parameter.value}}
      run: aws cloudfront create-invalidation --distribution-id ${{ env.DIST_ID }} --paths '/*'
      shell: bash
