name: Continuous deployment

on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Configure AWS credentials from Staging account
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.STAGING_DEPLOYER_ROLE_ARN }}
          aws-region: ca-central-1

      - name: Get host bucket name
        id: bucket
        run: |
          BUCKET_NAME_JSON=$(echo $(aws ssm get-parameter --name 'LandingPageStack_Bucket' --region 'ca-central-1') | sed 's/ //g' )
          echo "::set-output name=BUCKET_NAME::${BUCKET_NAME_JSON}"

      - name: Set bucket name variable
        env:
          bucket_name: ${{fromJson(steps.hostedzone.outputs.BUCKET_NAME).parameter.value}}

      - name: Sync to S3
        run: aws s3 sync ./dist s3://${{ env.bucket_name }}
        # run: aws s3 sync ./dist s3://${{ secrets.STAGING_BUCKET }}

      - name: Invalidate CloudFront distribution path
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.STAGING_CF_DIST_ID }} --paths '/*'
