name: Continuous deployment

on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Configure AWS credentials from Staging account
        uses: ./.github/actions/deploy
        with:
          roleArn: ${{ secrets.STAGING_DEPLOYER_ROLE_ARN }}
          bucketParamName: "LandingPageStack_Bucket"
          distributionSsmParamName: "LandingPageStack_Distribution_ID"

      # - name: Sync to S3
      #   env:
      #     BUCKET_NAME: ${{fromJson(steps.bucket.outputs.BUCKET_NAME).parameter.value}}
      #   run: aws s3 sync ./dist s3://${{ env.BUCKET_NAME }}

      # - name: Invalidate CloudFront distribution path
      #   env:
      #     DIST_ID: ${{fromJson(steps.dist.outputs.DIST_ID).parameter.value}}
      #   run: aws cloudfront create-invalidation --distribution-id ${{ env.DIST_ID }} --paths '/*'
