name: Continuous deployment

on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Configure AWS credentials from Staging account
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.STAGING_DEPLOYER_ROLE_ARN }}
          aws-region: ca-central-1

      - name: Get host bucket name
        id: bucket
        run: |
          BUCKET_NAME_JSON=$(echo $(aws ssm get-parameter --name 'LandingPageStack_Bucket' --region 'ca-central-1') | sed 's/ //g' )
          echo "::set-output name=BUCKET_NAME::${BUCKET_NAME_JSON}"

      - name: Set bucket name variable
        run: echo "${{fromJson(steps.bucket.outputs.BUCKET_NAME).parameter.value}}"
        env:
          bucket_name: ${{fromJson(steps.bucket.outputs.BUCKET_NAME).parameter.value}}

      - name: Print bucket name variable
        run: echo ${{ env.bucket_name }}

      - name: Sync to S3
        run: aws s3 sync ./dist s3://${{fromJson(steps.bucket.outputs.BUCKET_NAME).parameter.value}}
        # run: aws s3 sync ./dist s3://${{ secrets.STAGING_BUCKET }}

      - name: Invalidate CloudFront distribution path
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.STAGING_CF_DIST_ID }} --paths '/*'

      # - name: Get hosted zone ID
      #   id: hostedzone
      #   run: |
      #     JSON=$(echo $(aws ssm get-parameter --name 'Hosted_Zone_ID' --region 'us-east-1') | sed 's/ //g' )
      #     echo "::set-output name=HOSTED_ZONE_ID::${JSON}"

      # - name: Print hosted zone ID
      #   run: echo "${{fromJson(steps.hostedzone.outputs.HOSTED_ZONE_ID).parameter.value}}"
