name: Continuous deployment

on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Configure AWS credentials from Staging account
        uses: ./.github/actions/deploy
        with:
          roleArn: ${{ secrets.STAGING_DEPLOYER_ROLE_ARN }}

      # - name: Configure AWS credentials from Staging account
      #   uses: aws-actions/configure-aws-credentials@master
      #   with:
      #     role-to-assume: ${{ secrets.STAGING_DEPLOYER_ROLE_ARN }}
      #     aws-region: ca-central-1

      # - name: Get host bucket name
      #   id: bucket
      #   run: |
      #     BUCKET_NAME_JSON=$(echo $(aws ssm get-parameter --name 'LandingPageStack_Bucket' --region 'ca-central-1') | sed 's/ //g' )
      #     echo "::set-output name=BUCKET_NAME::${BUCKET_NAME_JSON}"

      # - name: Get CloudFront distribution ID
      #   id: dist
      #   run: |
      #     DIST_ID_JSON=$(echo $(aws ssm get-parameter --name 'LandingPageStack_Distribution_ID' --region 'ca-central-1') | sed 's/ //g' )
      #     echo "::set-output name=DIST_ID::${DIST_ID_JSON}"

      # - name: Sync to S3
      #   env:
      #     BUCKET_NAME: ${{fromJson(steps.bucket.outputs.BUCKET_NAME).parameter.value}}
      #   run: aws s3 sync ./dist s3://${{ env.BUCKET_NAME }}

      # - name: Invalidate CloudFront distribution path
      #   env:
      #     DIST_ID: ${{fromJson(steps.dist.outputs.DIST_ID).parameter.value}}
      #   run: aws cloudfront create-invalidation --distribution-id ${{ env.DIST_ID }} --paths '/*'
