name: Continuous deployment

on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Configure AWS credentials from Staging account
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.STAGING_DEPLOYER_ROLE_ARN }}
          aws-region: ca-central-1

      - name: Sync to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.STAGING_S3 }}

      - name: Invalidate CloudFront distribution path
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.STAGING_CF_DIST_ID }} --paths '/*'
