name: Continuous deployment

on: workflow_dispatch

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Configure AWS credentials from Staging account
        uses: 20hertz/static-site-actions@alpha
        # uses: ./.github/actions/deploy
        with:
          roleArn: ${{ secrets.STAGING_DEPLOYER_ROLE_ARN }}
          bucketSsmParamName: "LandingPageStack_Bucket"
          distributionSsmParamName: "LandingPageStack_Distribution_ID"
