name: Continuous deployment

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Deploy to staging
        if: github.ref == 'refs/heads/staging'
        uses: 20hertz/static-site-actions@gamma
        with:
          roleArn: ${{ secrets.STAGING_DEPLOYER_ROLE_ARN }}
          bucketSsmParamName: "LandingPageStack_Bucket"
          distributionSsmParamName: "LandingPageStack_Distribution_ID"

      - name: Deploy to prod
        if: github.ref == 'refs/heads/main'
        uses: 20hertz/static-site-actions@gamma
        with:
          roleArn: ${{ secrets.PROD_DEPLOYER_ROLE_ARN }}
          bucketSsmParamName: "LandingPageStack_Bucket"
          distributionSsmParamName: "LandingPageStack_Distribution_ID"
