name: Continuous deployment

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials from Staging account
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::925901147548:role/OIDCProviderStack-WebsiteDeployerRoleAC900FBE-42L6NN5E6TV0
          aws-region: ca-central-1

      - name: Sync to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.STAGING_S3 }}

      - name: Invalidate CloudFront distribution path
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.STAGING_CF_DIST_ID }} --paths '/*'
          
#       - name: Sync to S3
#         uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --follow-symlinks --delete
#         env:
#           AWS_S3_BUCKET: ${{ secrets.STAGING_S3 }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_SECRET_ACCESS_KEY }}
#           AWS_REGION: 'ca-central-1'
#           SOURCE_DIR: 'dist'

#       - name: Invalidate CloudFront distribution path
#         uses: chetan/invalidate-cloudfront-action@master
#         env:
#           DISTRIBUTION: ${{ secrets.STAGING_CF_DIST_ID }}
#           PATHS: '/*'
#           AWS_REGION: 'ca-central-1'
#           AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_SECRET_ACCESS_KEY }}
