name: Continuous deployment

on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Configure AWS credentials from Staging account
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.STAGING_DEPLOYER_ROLE_ARN }}
          aws-region: ca-central-1

      - name: Get hosted zone ID
        id: hostedzone
        run: echo "::set-output name=HOSTED_ZONE_ID::$(aws ssm get-parameter --name 'Hosted_Zone_ID' --region 'us-east-1').Parameter.Value"

      - name: Print hosted zone ID
        run: echo "${{ steps.hostedzone.outputs.HOSTED_ZONE_ID }}"

      - name: Sync to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.STAGING_BUCKET }}

      - name: Invalidate CloudFront distribution path
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.STAGING_CF_DIST_ID }} --paths '/*'
