name: Continuous deployment

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Use Node.js and cache modules
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Execute development build
        if: github.ref == 'refs/heads/staging'
        run: yarn build

      - name: Execute production build
        if: github.ref == 'refs/heads/main'
        run: NODE_ENV=production yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: dist

      - name: Deploy to staging
        if: github.ref == 'refs/heads/staging'
        uses: 20hertz/static-site-actions@main
        with:
          roleArn: ${{ secrets.STAGING_DEPLOYER_ROLE_ARN }}
          bucketSsmParamName: "LandingPageStack_Bucket"
          bucketPath: "/feed"
          distributionSsmParamName: "LandingPageStack_Distribution_ID"

      - name: Deploy to prod
        if: github.ref == 'refs/heads/main'
        uses: 20hertz/static-site-actions@gamma
        with:
          roleArn: ${{ secrets.PROD_DEPLOYER_ROLE_ARN }}
          bucketSsmParamName: "LandingPageStack_Bucket"
          distributionSsmParamName: "LandingPageStack_Distribution_ID"
